# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c60607034b5620630cc89ed0ba7cf64d41e7cf1d4cc52ab744b19a4821a3251516d2bae4ac299740b91927dd4e799afe053823e3da0eaf148ea04246f06b916c

test:
  secret_key_base: 2be4ec715258bb26a16c7e779c1f00a7adff4ad5ffec75397cda78aa794d9c16c2d1e203ccb680d63b8f9b1641c2bb0457b249d6396a439b00d63fefe8e4074b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
